<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Apple Store - Home</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="css/index.css">
</head>
<body>
	
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		
		<div class="container">
			<a class="navbar-brand" href="#">Apple Store</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="main.html">Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="about.html">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="contact.html">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>



	<div class="jumbotron jumbotron-fluid">
		<div class="container">
			<h1 class="display-4">Welcome to the Apple Store</h1>
			<p class="lead">We offer a wide range of Apple Products.</p>
			<div class="category-links">
				<a href="iphones.html" class="category-link">
					<img src="images/Category/Iphone.jpeg" alt="iPhones" class="category-image">
					<span class="category-title">iPhones</span>
				</a>
				<a href="macbooks.html" class="category-link">
					<img src="images/Category/macbooks.jpeg" alt="Macbooks" class="category-image">
					<span class="category-title">Macbooks</span>
				</a>
				<a href="AppleWatches.html" class="category-link">
					<img src="images/Category/applewatches.jpeg" alt="Apple Watches" class="category-image">
					<span class="category-title">Apple Watches</span>
				</a>
				<a href="Ipads.html" class="category-link">
					<img src="images/Category/ipad.jpeg" alt="iPads" class="category-image">
					<span class="category-title">iPads</span>
				</a>
				<a href="Airpods.html" class="category-link">
					<img src="images/Category/airpods.jpeg" alt="Airpods" class="category-image">
					<span class="category-title">Airpods</span>
				</a>
				<a href="Accessories.html" class="category-link">
					<img src="images/Category/Access.jpeg" alt="Accessories" class="category-image">
					<span class="category-title">Accessories</span>
				</a>
			</div>
		</div>
	</div>
	
	
	
	<footer class="bg-dark text-light pt-4 pb-2">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h4>Apple Store</h4>
					<p>Astana Expo, Astana, Kazakhstan</p>
					<p>Call us: +7 (705) 220-5830</p>
				</div>
				<div class="col-md-6">
					<h4>Follow Us</h4>
					<ul class="list-inline mb-0">
						<li class="list-inline-item"><a href="https://www.instagram.com/applestore.astana/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a></li>
						<li class="list-inline-item"><a href="https://www.facebook.com/AppStore/?locale=ru_RU" target="_blank"><i class="fab fa-facebook fa-2x"></i></a></li>
						<li class="list-inline-item"><a href="https://t.me/zhigerD" target="_blank"><i class="fab fa-telegram fa-2x"></i></a></li>
						<li class="list-inline-item"><a href="https://github.com/zhygerAITU" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
						
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
	
</body>
	
</html>

