<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Iphone Store - Home</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="css/index.css">
</head>
<body>
	
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		
		<div class="container">
			<a class="navbar-brand" href="#">Iphone Store</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="about.html">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="contact.html">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>



	<div class="jumbotron jumbotron-fluid">
		<div class="container">
			<h1 class="display-4">Welcome to the Iphone Store</h1>
			<p class="lead">We offer a wide range of Iphone models.</p>
			<a href="products.html" class="btn btn-primary btn-lg">Browse Products</a>
		</div>
	</div>
	<footer class="bg-dark text-light py-3">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h4>Iphone Store</h4>
					<p>Uly Dala 11/3, Astana, Kazakhstan</p>
					<p>Phone number: +7 (705) 220-5830</p>
				</div>
				<div class="col-md-6">
					<h4>Follow Us</h4>
					<ul class="list-inline">
						<li class="list-inline-item"><a href="https://instagram.com/dandeliodon?igshid=YmMyMTA2M2Y=" target="_blank"><i class="fab fa-instagram fa-2x"></i></a></li>
						<li class="list-inline-item"><a href="https://www.facebook.com/groups/ElonMusk/?locale=ru_RU" target="_blank"><i class="fab fa-facebook fa-2x"></i></a></li>
						<li class="list-inline-item"><a href="https://t.me/zhigerD" target="_blank"><i class="fab fa-telegram fa-2x"></i></a></li>
					</ul>
					<li class="list-inline-item"><a href="https://github.com/zhygerAITU" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
				</div>
			</div>
		</div>
	</footer>
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	
	<script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</body>
	
</html>

